# Site settings
title: InfiniD Blog
email: umangdhiman17@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/portfolio/" # the subpath of your site, e.g. /blog/
url: "http://InfiniD09.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
